# Project information
site_name: Kubescape
site_description: The official documentation for Kubescape
site_url: https://kubescape.io/

# Repository
repo_name: 'kubescape/kubescape'
repo_url: 'https://github.com/kubescape/kubescape'

# Config
theme:
  name: material
  logo: assets/kubescape-lockup.svg
  favicon: assets/favicon.svg
  font:
    text: Fira Sans
    code: Fira Mono
  features:
    - navigation.tabs    
    - navigation.footer  
  icon:
    repo: fontawesome/brands/github
  custom_dir: overrides
extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/@kubescape
    - icon: fontawesome/brands/github 
      link: https://github.com/kubescape/kubescape
  analytics:
    provider: google
    property: G-BS68QKB4RT
extra_css:
  - stylesheets/extra.css

# Copyright
copyright:
  Copyright &copy; 2021 - 2023 <a href="https://kubescape.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1">The Kubescape Authors</a>

nav:
    - Home: 'index.md'
    - Docs:
        - 'Documentation overview': 'docs/index.md'
        - 'Getting Started': 'docs/getting-started.md'
        - 'Installation': 'docs/installation.md'
    - Project: 
        - 'About the Kubescape project': 'project/about.md'
        - 'License': 'project/license.md'
        - 'Community': 'project/community.md'
        - 'Contributing': 'https://github.com/kubescape/kubescape/blob/master/CONTRIBUTING.md'
    - GitHub: 'https://github.com/kubescape/kubescape'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences    